Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.provision 'shell', path: 'ensure.guest.has.ansible.sh'

  # Synced Folder required for use with Hyper-V Provider
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provision 'ansible_local' do |ansible|
    ansible.become = true
    ansible.playbook = 'cli-only.yml'
    # ansible.verbose = "vvv"
  end
end
