Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "snappy"

  config.vm.provision "shell", inline: $install_group
  config.vm.provision "shell", inline: $install_docker_snap
end

$install_group = <<-SHELL
  sudo addgroup --system docker
  sudo adduser vagrant docker
SHELL

$install_docker_snap = <<-SHELL
  sudo snap refresh
  sudo snap install docker
SHELL
