Vagrant.configure("2") do |config|

  # Hyper-V Provider Specific Configuration
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.linked_clone = true
    h.memory = 2048
    h.maxmemory = 2048
  end

  # Virtualbox Provider Specific Configuration
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "binaries" do |binaries|
    binaries.vm.box = "generic/ubuntu2204"
    binaries.vm.hostname = "binaries"

    # Hyper-V Box Specific Configuration
    binaries.vm.provider 'hyperv' do |h, override|
      override.vm.network "public_network", bridge: "Default Switch"
    end

    # Virtualbox Box Specific Configuration
    binaries.vm.provider 'virtualbox' do |v, override|
      override.vm.synced_folder ".", "/vagrant"
    end
  end

  config.vm.provision "shell", path: "install.from.binaries.sh"
end
