Vagrant.configure("2") do |config|
  config.vm.define "binaries" do |binaries|
    binaries.vm.box = "generic/ubuntu2004"
    binaries.vm.hostname = "binaries"
  end

  # Second Machine Definition
  # config.vm.define "placeholder" do |placeholder|
  #   binaries.vm.box = "generic/ubuntu2004"
  #   binaries.vm.hostname = "placeholder"
  # end

  config.vm.provision "shell", path: "install.from.binaries.sh"
end
