# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Hyper-V Provider Specific Configuration
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.linked_clone = true
    h.memory = 2048
    h.maxmemory = 2048
  end

  # Virtualbox Provider Specific Configuration
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # VMware Workstation Provider Specific Configuration
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = 2048
    v.vmx["numvcpus"] = 2
  end

  config.vm.define "clionly" do |clionly|
    # VM Shared Configuration
    clionly.vm.box = "generic/ubuntu2204"
    clionly.vm.hostname = "clionly"

    # Hyper-V VM Specific Configuration
    clionly.vm.provider 'hyperv' do |h, override|
      override.vm.synced_folder ".", "/vagrant", type: "rsync"
      override.vm.network "public_network", bridge: "Default Switch"
    end

    # Virtualbox VM Specific Configuration
    clionly.vm.provider 'virtualbox' do |v, override|
      override.vm.synced_folder ".", "/vagrant"
    end

    # VMware Workstation VM Specific Configuration
    clionly.vm.provider 'vmware_desktop' do |v, override|
      override.vm.synced_folder ".", "/vagrant"
    end
  end

  # VM Shared Provisioning
  config.vm.provision 'shell', path: 'ensure.guest.has.ansible.sh'
  config.vm.provision 'ansible_local' do |ansible|
    ansible.become = true
    ansible.playbook = 'cli-only.yml'
    # ansible.verbose = "vvv"
  end
end
