# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "getdc" do |getdc|
    getdc.vm.box = "generic/ubuntu2004"
    getdc.vm.hostname = "getdc"
  end

  config.vm.provision "shell", path: "config.learn.ubuntu.sh", name: "learns"
  config.vm.provision "shell", path: "https://get.docker.com", name: "dockers"
  config.vm.provision "shell", path: "config.docker.after.install.sh", name: "afters"
end
